# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

version: "3.4"

services:
  collectd:
    image: ${DOCKER_REGISTRY}/collectd:latest
    privileged: true
    hostname: ${HOSTNAME}
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - HOST_TYPE=VM-${EDGE_ID}
    volumes:
      - /proc:/mnt/proc
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/tmp:/var/tmp

